[package]
name = "ecs-core-rust"
version = "0.0.1"
edition = "2021"
description = "基于Rust和WebAssembly的高性能ECS框架核心实现"
authors = ["yhh"]
license = "MIT"
repository = "https://github.com/esengine/ecs-framework.git"
keywords = ["ecs", "entity-component-system", "game-engine", "wasm", "webassembly"]

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
out-name = "ecs-core-rust"

[package.metadata.wasm-pack]
name = "@esengine/ecs-framework-wasm"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
js-sys = "0.3"
web-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
serde_json = "1.0"
rustc-hash = "1.1"
console_error_panic_hook = { version = "0.1.7", optional = true }

[features]
default = ["console_error_panic_hook"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false